# Introduction to PyTorch

# Linear Regression with PyTorch

In [0]:
import torch
import torch.nn as nn

# Defining the Linear Regression Model

class LReg(nn.Module):
  def __init__(self):
    super().__init__()
    self.m = nn.Parameter(torch.randn((1)))
    self.c = nn.Parameter(torch.randn((1)))

  def forward(self, x): 
    return (self.m * x) + self.c

# Initialize the Model
net = LReg()

 Define the Loss functions

In [0]:
# We will use a simple Mean Squared Error
def mse(preds, target):
  se = ((preds - target.float()) ** 2).sum()
  return se / len(preds)

 Define a synthetic Dataset

In [0]:
from torch.utils.data import DataLoader
from torch.utils.data import TensorDataset

x = torch.arange(1, 1000)
y = x * 2
tr = TensorDataset(x, y)
tloader = DataLoader(tr, batch_size=4, shuffle=True)

x = torch.arange(5000, 6000)
y = x * 2
va = TensorDataset(x, y)
vloader = DataLoader(va, batch_size=4, shuffle=True)

 Define function to train model

In [0]:
import torch.optim as optim

def train(net, crit, trl, val, epochs=5, lr=0.01):
  # Initialize the Optimizer
  opt = optim.Adam(net.parameters(), lr=lr)
  
  dev = 'cuda' if torch.cuda.is_available() else 'cpu'
  
  net.to(dev)
  net.train()
  
  for i in range(epochs):
    
    for data, labl in trl:
      data, labl = data.to(dev), labl.to(dev)
      
      out = net(data.float())
      
      loss = crit(out, labl)
      
      opt.zero_grad()
      loss.backward()
      opt.step()
    
    
    with torch.no_grad():
      net.eval()
      acc = 0; vloss = 0;
      
      for data, labl in val:
        data, labl = data.to(dev), labl.to(dev)
        
        out = net(data.float())
        
        vloss += crit(out, labl).detach().cpu().numpy().item()
      
      vloss /= (len(val) * val.batch_size)
      
      print ('Epoch {}/{} - Validation Loss {:.7f}'.format(i+1, epochs, vloss))

 Train the model on the Synthetic Dataset

In [20]:
train(net, mse, tloader, vloader, epochs=50, lr=0.01)

Epoch 1/50 - Validation Loss 0.0002387
Epoch 2/50 - Validation Loss 0.0000369
Epoch 3/50 - Validation Loss 0.0000020
Epoch 4/50 - Validation Loss 0.0002587
Epoch 5/50 - Validation Loss 0.0000038
Epoch 6/50 - Validation Loss 22.3764328
Epoch 7/50 - Validation Loss 0.0049550
Epoch 8/50 - Validation Loss 0.0137209
Epoch 9/50 - Validation Loss 0.0029852
Epoch 10/50 - Validation Loss 0.0000545
Epoch 11/50 - Validation Loss 0.0000026
Epoch 12/50 - Validation Loss 0.0000002
Epoch 13/50 - Validation Loss 0.0000000
Epoch 14/50 - Validation Loss 0.0000000
Epoch 15/50 - Validation Loss 0.0000000
Epoch 16/50 - Validation Loss 0.0000000
Epoch 17/50 - Validation Loss 0.0000000
Epoch 18/50 - Validation Loss 0.0000000
Epoch 19/50 - Validation Loss 0.0000000
Epoch 20/50 - Validation Loss 0.0000000
Epoch 21/50 - Validation Loss 0.0000000
Epoch 22/50 - Validation Loss 0.0000000
Epoch 23/50 - Validation Loss 0.0000000
Epoch 24/50 - Validation Loss 0.0000000
Epoch 25/50 - Validation Loss 0.0000000
Epoch 26

 Test it on a number

In [22]:
number_to_test = 32312.
net.cpu()
with torch.no_grad():
  net.eval()
  inp_tensor = torch.Tensor([number_to_test])
  print (net(inp_tensor).item())

tensor([64624.])


In [23]:
net.m

Parameter containing:
tensor([2.], requires_grad=True)

In [24]:
net.c

Parameter containing:
tensor([9.5707e-08], requires_grad=True)